import { createContext } from "react";

const countries = [
  { title: "Afghanistan", code: "AF" },
  { title: "Albania", code: "AL" },
  { title: "Algeria", code: "DZ" },
  { title: "Angola", code: "AO" },
  { title: "Argentina", code: "AR" },
  { title: "Armenia", code: "AM" },
  { title: "Australia", code: "AU" },
  { title: "Austria", code: "AT" },
  { title: "Azerbaijan", code: "AZ" },
  { title: "Bahamas", code: "BS" },
  { title: "Bangladesh", code: "BD" },
  { title: "Belarus", code: "BY" },
  { title: "Belgium", code: "BE" },
  { title: "Belize", code: "BZ" },
  { title: "Benin", code: "BJ" },
  { title: "Bhutan", code: "BT" },
  { title: "Bolivia", code: "BO" },
  { title: "Bosnia and Herzegovina", code: "BA" },
  { title: "Botswana", code: "BW" },
  { title: "Brazil", code: "BR" },
  { title: "Brunei Darussalam", code: "BN" },
  { title: "Bulgaria", code: "BG" },
  { title: "Burkina Faso", code: "BF" },
  { title: "Burundi", code: "BI" },
  { title: "Cambodia", code: "KH" },
  { title: "Cameroon", code: "CM" },
  { title: "Canada", code: "CA" },
  { title: "Central African Republic", code: "CF" },
  { title: "Chad", code: "TD" },
  { title: "Chile", code: "CL" },
  { title: "China", code: "CN" },
  { title: "Colombia", code: "CO" },
  { title: "Congo", code: "CG" },
  { title: "Democratic Republic of Congo", code: "CD" },
  { title: "Costa Rica", code: "CR" },
  { title: "Ivory Coast", code: "CI" },
  { title: "Croatia", code: "HR" },
  { title: "Cuba", code: "CU" },
  { title: "Cyprus", code: "CY" },
  { title: "Czechia", code: "CZ" },
  { title: "Denmark", code: "DK" },
  { title: "Djibouti", code: "DJ" },
  { title: "Dominican Republic", code: "DO" },
  { title: "Ecuador", code: "EC" },
  { title: "Egypt", code: "EG" },
  { title: "El Salvador", code: "SV" },
  { title: "Equatorial Guinea", code: "GQ" },
  { title: "Eritrea", code: "ER" },
  { title: "Estonia", code: "EE" },
  { title: "Ethiopia", code: "ET" },
  { title: "Falkland Islands", code: "FK" },
  { title: "Fiji", code: "FJ" },
  { title: "Finland", code: "FI" },
  { title: "France", code: "FR" },
  { title: "French Guiana", code: "GF" },
  { title: "French Southern Territories", code: "TF" },
  { title: "Gabon", code: "GA" },
  { title: "Gambia", code: "GM" },
  { title: "Georgia", code: "GE" },
  { title: "Germany", code: "DE" },
  { title: "Ghana", code: "GH" },
  { title: "Greece", code: "GR" },
  { title: "Greenland", code: "GL" },
  { title: "Guatemala", code: "GT" },
  { title: "Guinea", code: "GN" },
  { title: "Guinea-Bissau", code: "GW" },
  { title: "Guyana", code: "GY" },
  { title: "Haiti", code: "HT" },
  { title: "Honduras", code: "HN" },
  { title: "Hungary", code: "HU" },
  { title: "Iceland", code: "IS" },
  { title: "India", code: "IN" },
  { title: "Indonesia", code: "ID" },
  { title: "Iraq", code: "IQ" },
  { title: "Ireland", code: "IE" },
  { title: "Israel", code: "IL" },
  { title: "Italy", code: "IT" },
  { title: "Jamaica", code: "JM" },
  { title: "Japan", code: "JP" },
  { title: "Jordan", code: "JO" },
  { title: "Kazakhstan", code: "KZ" },
  { title: "Kenya", code: "KE" },
  { title: "South Korea", code: "KR" },
  { title: "Kuwait", code: "KW" },
  { title: "Kyrgyzstan", code: "KG" },
  { title: "Lao", code: "LA" },
  { title: "Latvia", code: "LV" },
  { title: "Lebanon", code: "LB" },
  { title: "Lesotho", code: "LS" },
  { title: "Liberia", code: "LR" },
  { title: "Libya", code: "LY" },
  { title: "Lithuania", code: "LT" },
  { title: "Luxembourg", code: "LU" },
  { title: "Macedonia", code: "MK" },
  { title: "Madagascar", code: "MG" },
  { title: "Malawi", code: "MW" },
  { title: "Malaysia", code: "MY" },
  { title: "Mali", code: "ML" },
  { title: "Mauritania", code: "MR" },
  { title: "Mexico", code: "MX" },
  { title: "Moldova", code: "MD" },
  { title: "Mongolia", code: "MN" },
  { title: "Montenegro", code: "ME" },
  { title: "Morocco", code: "MA" },
  { title: "Mozambique", code: "MZ" },
  { title: "Myanmar", code: "MM" },
  { title: "Namibia", code: "NA" },
  { title: "Nepal", code: "NP" },
  { title: "Netherlands", code: "NL" },
  { title: "New Caledonia", code: "NC" },
  { title: "New Zealand", code: "NZ" },
  { title: "Nicaragua", code: "NI" },
  { title: "Niger", code: "NE" },
  { title: "Nigeria", code: "NG" },
  { title: "Norway", code: "NO" },
  { title: "Oman", code: "OM" },
  { title: "Pakistan", code: "PK" },
  { title: "Palestine", code: "PS" },
  { title: "Panama", code: "PA" },
  { title: "Papua New Guinea", code: "PG" },
  { title: "Paraguay", code: "PY" },
  { title: "Peru", code: "PE" },
  { title: "Philippines", code: "PH" },
  { title: "Poland", code: "PL" },
  { title: "Portugal", code: "PT" },
  { title: "Puerto Rico", code: "PR" },
  { title: "Qatar", code: "QA" },
  { title: "Republic of Kosovo", code: "XK" },
  { title: "Romania", code: "RO" },
  { title: "Rwanda", code: "RW" },
  { title: "Saudi Arabia", code: "SA" },
  { title: "Senegal", code: "SN" },
  { title: "Serbia", code: "RS" },
  { title: "Sierra Leone", code: "SL" },
  { title: "Slovakia", code: "SK" },
  { title: "Slovenia", code: "SI" },
  { title: "Solomon Islands", code: "SB" },
  { title: "Somalia", code: "SO" },
  { title: "South Africa", code: "ZA" },
  { title: "South Sudan", code: "SS" },
  { title: "Spain", code: "ES" },
  { title: "Sri Lanka", code: "LK" },
  { title: "Sudan", code: "SD" },
  { title: "Suriname", code: "SR" },
  { title: "Svalbard and Jan Mayen", code: "SJ" },
  { title: "Swaziland", code: "SZ" },
  { title: "Sweden", code: "SE" },
  { title: "Switzerland", code: "CH" },
  { title: "Syrian Arab Republic", code: "SY" },
  { title: "Taiwan", code: "TW" },
  { title: "Tajikistan", code: "TJ" },
  { title: "Tanzania", code: "TZ" },
  { title: "Thailand", code: "TH" },
  { title: "Timor-Leste", code: "TL" },
  { title: "Togo", code: "TG" },
  { title: "Trinidad and Tobago", code: "TT" },
  { title: "Tunisia", code: "TN" },
  { title: "Turkey", code: "TR" },
  { title: "Turkmenistan", code: "TM" },
  { title: "Uganda", code: "UG" },
  { title: "Ukraine", code: "UA" },
  { title: "United Kingdom", code: "GB" },
  { title: "USA", code: "US" },
  { title: "Uruguay", code: "UY" },
  { title: "Uzbekistan", code: "UZ" },
  { title: "Vanuatu", code: "VU" },
  { title: "Venezuela", code: "VE" },
  { title: "Western Sahara", code: "EH" },
  { title: "Yemen", code: "YE" },
  { title: "Zambia", code: "ZM" },
  { title: "Zimbabwe", code: "ZW" },
  { title: "Singapore", code: "SG" },
  { title: "Hong Kong", code: "HK" },
  { title: "Diamond Princess", code: "DP" },
  { title: "Iran", code: "IR" },
  { title: "North Korea", code: "KP" },
  { title: "Russia", code: "RU" },
  { title: "UAE", code: "AE" },
  { title: "Vietnam", code: "VN" },
];

const CountryContext = createContext(countries);

export default CountryContext;
